---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./deploy/helloworld
  prune: true
  sourceRef:
    kind: GitRepository
    name: helloworld
  validation: client

